In [7]:
class employee:
    def __init__(self):
        self.empid=int(input("enter the id"))
        self.name=input("enter the name")
        self.basicsalary=int(input("enter the salary"))
        self.experience=int(input("enter the experience"))
        self.hra=0
        self.da=0
        self.pf=0
        self.total=0
        self.bonus=0
    def calculate(self):
        self.hra=0.35*self.basicsalary
        self.da=0.58*self.basicsalary
        self.pf=0.095*self.basicsalary
    def display(self):
        print("hr is ",self.hra,"da is",self.da, "pf is",self.pf)

    def calbonus(self):
        if self.experience>=30:
            self.bonus=0.59*self.basicsalary
            print("bonus",self.bonus)
        elif self.experience>=23:
            self.bonus=0.51*self.basicsalary
            print("bonus",self.bonus)
        elif self.experience>=15:
            self.bonus=0.45*self.basicsalary
            print("bonus",self.bonus)
        elif self.experience>=7:
            self.bonus=0.33*self.basicsalary
            print("bonus",self.bonus)
        elif self.experience<7:
            self.bonus=0.16*self.basicsalary
            print("bonus",self.bonus)

    def netsalary(self):
        self.total=self.basicsalary+self.da+self.hra-self.pf+self.bonus 
        print("netsalary",self.total)

teerth=employee()
teerth.calculate()
teerth.display()
teerth.calbonus()
teerth.netsalary()

enter the id121
enter the nameteerth
enter the salary56000
enter the experience45
hr is  19600.0 da is 32479.999999999996 pf is 5320.0
bonus 33040.0
netsalary 135800.0


In [1]:
numbers = [float(input(f"Enter number {i + 1}: ")) for i in range(8)]
newlist = [numbers[i] + numbers[7 - i] for i in range(4)]
newlist = list(set(newlist))
print("Result Tuple:", tuple(newlist))\

    

Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 5
Enter number 6: 6
Enter number 7: 7
Enter number 8: 8
Result Tuple: (9.0,)


In [18]:
class number:
    def __init__ (self,num=0):
        self.num=num
        
    def setnum(self,num):
        self.num=num
        
    def getname(self):
        return self.num
    
    def add(self,n2):
        return self.num+n2.num
         
    def power(self,n2):
        return self.num**n2.num
      
    def concat (self,n2):
        return str(self.num)+str(n2.num)
    
    def min1 (self,n2):
        return (min(self.num,n2.num))
    
    def max1 (self,n2):
        return (max(self.num,n2.num))
n1=number()
n1.setnum(9)
n2=number()
n2.setnum(2)
n1.add(n2)

print(f'Addition {n1.add(n2)}')

print("power is" , n1.power(n2))

print("concat is" , n1.concat(n2))

print("min1 is" , n1.min1(n2))

print("max1 is" , n1.max1(n2))

Addition 11
power is 81
concat is 92
min1 is 2
max1 is 9


In [12]:
data=[(12345,"Diksha","Dikshar@nuv.ac.in"),
     (45557,"Jiva","Jiva@nuv.ac.in"),
     (16789,"Ronit","Ronitd@nuv.ac.in"),
     (69433,"Heena","heena@nuv.ac.in")
     ]

def search_by_id(sid):
    for d in data:
        if d[0]==sid:
            print(d)
            
def search_by_name(name):
    for d in data: 
        if d[1]==name:
            print(d)
        
sid=int(input("enter the sid="))
search_by_id(sid)
            
name=input("enter the name")
search_by_name(name)


enter the sid=69433
(69433, 'Heena', 'heena@nuv.ac.in')
enter the nameDiksha
(12345, 'Diksha', 'Dikshar@nuv.ac.in')


In [16]:
mydict={"Enrollment id" :[12345,45667,16789,69433],
        "Student Name" :["Diksha","Jiva","Ronit","Heena"],
        "Email Id" :["Diksha r@nuv.ac.in","Jiva@nuv.ac.in","Ronitd@nuv.ac.in","Heena@nuv.ac.in"]
    
}

mydict["Enrollment id"][0]
value=int(input("enter the id"))
for i in range(len(mydict["Enrollment id"])):
    if mydict["Enrollment id"][i]==value:
        print(mydict["Enrollment id"][i])
        print(mydict["Student Name"][i])
        print(mydict["Email Id"][i])

enter the id12345
12345
Diksha
Diksha r@nuv.ac.in


In [1]:
data=[
    (12345,"diksha","diksha r@nuv.ac.in"),
      (45667,"jiva","jiva@nuv.ac.in"),
      (16789,"Ronit","Ronitd@nuv.ac.in"),
      (69433,"Heena","Heena@nuv.ac.in")
    ]
mydict={"Enroll":[],
        "Name":[],
        
        "email":[]}

for d in data:
    mydict["Enroll"].append(d[0])
    mydict["Name"].append(d[1])
    mydict["email"].append(d[2])
mydict

{'Enroll': [12345, 45667, 16789, 69433],
 'Name': ['diksha', 'jiva', 'Ronit', 'Heena'],
 'email': ['diksha r@nuv.ac.in',
  'jiva@nuv.ac.in',
  'Ronitd@nuv.ac.in',
  'Heena@nuv.ac.in']}

In [2]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.84580379])

In [10]:
np.random.rand(25)

array([0.74100344, 0.60683739, 0.23759973, 0.57316601, 0.35602555,
       0.63128953, 0.44055514, 0.03196027, 0.21681073, 0.3134074 ,
       0.95112213, 0.73743106, 0.4625859 , 0.73564861, 0.0808639 ,
       0.41192299, 0.1433194 , 0.64668863, 0.63763246, 0.5032119 ,
       0.05214325, 0.52933019, 0.78167014, 0.77503059, 0.63743961])

In [11]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [2]:
import numpy as np
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
arr[3,4]

20

In [19]:
arr[4:5]

array([[21, 22, 23, 24, 25]])

In [20]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
np.sum(arr)

325

In [22]:
np.std(arr)

7.211102550927978

axis=1 for rows and axis=0 for column

In [23]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [24]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115])

In [26]:
oneD=np.arange(0,12)
oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
twoD=np.arange(0,12).reshape(3,4)
twoD

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
threeD=np.arange(0,12).reshape(3,2,2)
threeD

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [30]:
oneD.dtype
twoD.dtype
threeD.dtype

dtype('int32')

In [31]:
oneD.shape

(12,)

In [32]:
twoD.shape

(3, 4)

In [33]:
threeD.shape

(3, 2, 2)

In [34]:
oneD.ndim

1

In [35]:
twoD.ndim

2

In [36]:
threeD.ndim

3

In [38]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
math=np.random.randint(0,100,20)
math

array([19, 51, 16, 45, 55, 48, 78, 96,  2,  4, 59, 73, 40, 86,  9, 48, 69,
       89, 31, 17])

In [44]:
sort=np.sort(math)
sort

array([ 2,  4,  9, 16, 17, 19, 31, 40, 45, 48, 48, 51, 55, 59, 69, 73, 78,
       86, 89, 96])

In [45]:
np.flip(sort)

array([96, 89, 86, 78, 73, 69, 59, 55, 51, 48, 48, 45, 40, 31, 19, 17, 16,
        9,  4,  2])

In [46]:
copy1=np.copy(sort)
copy1

array([ 2,  4,  9, 16, 17, 19, 31, 40, 45, 48, 48, 51, 55, 59, 69, 73, 78,
       86, 89, 96])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [3]:
one=np.arange(1,10).reshape(3,3)
np.append(one,[[10,11,12]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.vstack((one,[10,11,12]))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.hstack((one,[[10],[11],[12]]))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [7]:
np.vsplit(one,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [11]:
np.hsplit(one,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [12]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [17]:
Q13=np.random.uniform(1,20,10)
Q13
##uniform is for random float values##

array([ 6.07128582,  8.30288536,  1.97320242, 10.1734273 , 13.96463847,
       11.69418223, 18.43114581, 18.40703277, 14.19052305,  6.78870037])

In [18]:
np.ceil(Q13)

array([ 7.,  9.,  2., 11., 14., 12., 19., 19., 15.,  7.])

In [19]:
np.floor(Q13)

array([ 6.,  8.,  1., 10., 13., 11., 18., 18., 14.,  6.])

In [20]:
np.round(Q13,decimals=2)

array([ 6.07,  8.3 ,  1.97, 10.17, 13.96, 11.69, 18.43, 18.41, 14.19,
        6.79])

In [23]:
m=np.arange(0,25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
m.min(axis=0)

array([0, 1, 2, 3, 4])

In [25]:
m.max(axis=0)

array([20, 21, 22, 23, 24])

In [26]:
m.var(axis=0)

array([50., 50., 50., 50., 50.])

In [27]:
m.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [4]:
Q15 = np.full((10,), None)
Q15[5] = 200
print(Q15)

[None None None None None 200 None None None None]


In [20]:
a=np.arange(100,150)

In [18]:
np.flip(a)

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [25]:
Q18=np.arange(0,25).reshape(5,5)
Q18

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
Q19=np.nonzero([1,0,2,0,0,4,0,8])
Q19

(array([0, 2, 5, 7], dtype=int64),)

In [9]:
mat=np.ones((10,10))
mat[]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
mat[1:9,1:9]=0
mat

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
Q21=np.ones((8,8))
Q21[::2,::2]=0
Q21[1::2,1::2]=0
Q21

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [41]:
mat1=np.random.randint(0,10,9).reshape(3,3)
mat2=np.random.randint(0,10,9).reshape(3,3)
mat1

array([[1, 4, 2],
       [7, 3, 9],
       [0, 2, 5]])

In [42]:
mat2

array([[7, 2, 2],
       [0, 9, 4],
       [7, 6, 4]])

In [43]:
sum=mat1+mat2
sum

array([[ 8,  6,  4],
       [ 7, 12, 13],
       [ 7,  8,  9]])

In [44]:
mul=mat1@mat2
mul

array([[ 21,  50,  26],
       [112,  95,  62],
       [ 35,  48,  28]])

In [48]:
sub=mat1-mat2
sub

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
a=np.ones((10,10))
a[::2,::2]=-1
a[1::2,1::2]=1
a

array([[-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

PANDAS

In [1]:
import pandas as pd
import numpy as np

In [2]:
marks=pd.Series([30,39,40], index=["PYTHON","DSA","DBMS"])
marks

PYTHON    30
DSA       39
DBMS      40
dtype: int64

In [3]:
marks.keys()

Index(['PYTHON', 'DSA', 'DBMS'], dtype='object')

In [4]:
marks.values

array([30, 39, 40], dtype=int64)

In [5]:
type(marks)

pandas.core.series.Series

In [6]:
d={"name":'Teerth',"cource":'BCA',"Address":'Vadodara'}
student=pd.Series(d)

In [7]:
student.keys()

Index(['name', 'cource', 'Address'], dtype='object')

In [8]:
student.values

array(['Teerth', 'BCA', 'Vadodara'], dtype=object)

In [9]:
np.random.seed(1)
df=pd.DataFrame(np.random.randint(1,100,(4,3)),index=['Teerth','Naitik','Riya','Fenil'],columns=['python','Data Science','DBMS'])
df

python  Data Science  DBMS
Teerth      38            13    73
Naitik      10            76     6
Riya        80            65    17
Fenil        2            77    72

In [10]:
df['DBMS']

Teerth    73
Naitik     6
Riya      17
Fenil     72
Name: DBMS, dtype: int32

In [11]:
df[['python','Data Science']]

python  Data Science
Teerth      38            13
Naitik      10            76
Riya        80            65
Fenil        2            77

In [12]:
df.loc[['Teerth','Naitik']]

python  Data Science  DBMS
Teerth      38            13    73
Naitik      10            76     6

In [13]:
df["Name"]=["Naitik","Teerth","Riya","Fenil"]
df

python  Data Science  DBMS    Name
Teerth      38            13    73  Naitik
Naitik      10            76     6  Teerth
Riya        80            65    17    Riya
Fenil        2            77    72   Fenil

In [14]:
df["Total"]=df["python"]+df["Data Science"]+df["DBMS"]
df

python  Data Science  DBMS    Name  Total
Teerth      38            13    73  Naitik    124
Naitik      10            76     6  Teerth     92
Riya        80            65    17    Riya    162
Fenil        2            77    72   Fenil    151

In [15]:
df["Percentage"]=((df["python"]+df["Data Science"]+df["DBMS"])/300)*100
df

python  Data Science  DBMS    Name  Total  Percentage
Teerth      38            13    73  Naitik    124   41.333333
Naitik      10            76     6  Teerth     92   30.666667
Riya        80            65    17    Riya    162   54.000000
Fenil        2            77    72   Fenil    151   50.333333

In [16]:
df.drop('Percentage',axis=1)

python  Data Science  DBMS    Name  Total
Teerth      38            13    73  Naitik    124
Naitik      10            76     6  Teerth     92
Riya        80            65    17    Riya    162
Fenil        2            77    72   Fenil    151

In [17]:
df.drop('Percentage',axis=1,inplace=True)

In [18]:
df

python  Data Science  DBMS    Name  Total
Teerth      38            13    73  Naitik    124
Naitik      10            76     6  Teerth     92
Riya        80            65    17    Riya    162
Fenil        2            77    72   Fenil    151

In [19]:
df2=pd.read_csv("data.csv")
df2

stateid            name  population in crores  No. of Universities
0    12001         Gujarat                    10                   29
1    12002     Maharashtra                    19                   36
2    12003       Rajasthan                    13                   31
3    12004  Madhya Pradesh                    14                   21
4    12005          Punjab                    12                   13
5    12006       Karnataka                    23                   31
6    12007       Tamilnadu                    25                   29
7    12008          Kerala                    21                   15

Assignment

In [20]:
np.random.seed(1)
df1=pd.DataFrame(np.random.randint(1,100,(5,3)),index=['Element 1','Element 2','Element 3','Element 4','Element 5'],columns=['Product ID','Product Name','Product Price'])
df1

Product ID  Product Name  Product Price
Element 1          38            13             73
Element 2          10            76              6
Element 3          80            65             17
Element 4           2            77             72
Element 5           7            26             51

In [21]:
df1.loc["Element 1"]


Product ID       38
Product Name     13
Product Price    73
Name: Element 1, dtype: int32

In [22]:
df1.loc["Element 2"]

Product ID       10
Product Name     76
Product Price     6
Name: Element 2, dtype: int32

In [23]:
df1.loc["Element 3"]

Product ID       80
Product Name     65
Product Price    17
Name: Element 3, dtype: int32

In [24]:
df1.loc["Element 4"]

Product ID        2
Product Name     77
Product Price    72
Name: Element 4, dtype: int32

In [25]:
df1.loc["Element 5"]

Product ID        7
Product Name     26
Product Price    51
Name: Element 5, dtype: int32

In [26]:
df1["Product Name"]

Element 1    13
Element 2    76
Element 3    65
Element 4    77
Element 5    26
Name: Product Name, dtype: int32

In [27]:
df1["Product Price"]

Element 1    73
Element 2     6
Element 3    17
Element 4    72
Element 5    51
Name: Product Price, dtype: int32

In [28]:
df1.loc["Element 3":]

Product ID  Product Name  Product Price
Element 3          80            65             17
Element 4           2            77             72
Element 5           7            26             51

In [29]:
df1.iloc[2,2]
df1.loc['Element 2':,['Product Price']]

Product Price
Element 2              6
Element 3             17
Element 4             72
Element 5             51

In [30]:
df1.loc['Element 2':'Element 4',df1.columns!='Product Price']

Product ID  Product Name
Element 2          10            76
Element 3          80            65
Element 4           2            77

In [31]:
df1.iloc[0:3,[2]]

Product Price
Element 1             73
Element 2              6
Element 3             17

In [32]:
df=pd.DataFrame(np.random.randint(1,100,(4,3)),index=['Teerth','Naitik','Riya','Fenil'],columns=['python','Data Science','DBMS'])
df

python  Data Science  DBMS
Teerth      21            19    85
Naitik      12            29    30
Riya        15            51    69
Fenil       88            88    95

In [33]:
df['python']<40

Teerth     True
Naitik     True
Riya       True
Fenil     False
Name: python, dtype: bool

In [34]:
df[df['python']<40]

python  Data Science  DBMS
Teerth      21            19    85
Naitik      12            29    30
Riya        15            51    69

In [35]:
df.loc[df['python']<40,'python']=41

In [36]:
df

python  Data Science  DBMS
Teerth      41            19    85
Naitik      41            29    30
Riya        41            51    69
Fenil       88            88    95

In [37]:
df3=df+10

In [38]:
df3

python  Data Science  DBMS
Teerth      51            29    95
Naitik      51            39    40
Riya        51            61    79
Fenil       98            98   105

In [39]:
df3[df3>100]=100

In [40]:
df3

python  Data Science  DBMS
Teerth      51            29    95
Naitik      51            39    40
Riya        51            61    79
Fenil       98            98   100

In [41]:
df3[(df3['python']>50) & (df3['Data Science']>60)]

python  Data Science  DBMS
Riya       51            61    79
Fenil      98            98   100

In [42]:
df3[df3.index.str.startswith('T')]

python  Data Science  DBMS
Teerth      51            29    95

In [43]:
df3[df3.index.str.endswith('a')]

python  Data Science  DBMS
Riya      51            61    79

In [44]:
df3["Total"]=((df3["python"]+df3["Data Science"]+df3["DBMS"]))

In [45]:
df3

python  Data Science  DBMS  Total
Teerth      51            29    95    175
Naitik      51            39    40    130
Riya        51            61    79    191
Fenil       98            98   100    296

In [46]:
df3["Percentage"]=((df3["python"]+df3["Data Science"]+df3["DBMS"])/300)*100

In [47]:
df3

python  Data Science  DBMS  Total  Percentage
Teerth      51            29    95    175   58.333333
Naitik      51            39    40    130   43.333333
Riya        51            61    79    191   63.666667
Fenil       98            98   100    296   98.666667

In [48]:
df3['Result']=np.where(df3['Percentage']<45,"Fail","Pass")
df3

python  Data Science  DBMS  Total  Percentage Result
Teerth      51            29    95    175   58.333333   Pass
Naitik      51            39    40    130   43.333333   Fail
Riya        51            61    79    191   63.666667   Pass
Fenil       98            98   100    296   98.666667   Pass

In [49]:
df3.loc[df3['Percentage']<50,'Grade']='F'
df3.loc[df3['Percentage']>=50,'Grade']='E'
df3.loc[df3['Percentage']>=60,'Grade']='D'
df3.loc[df3['Percentage']>=70,'Grade']='C'
df3.loc[df3['Percentage']>=80,'Grade']='B'
df3.loc[df3['Percentage']>=90,'Grade']='A'
df3

python  Data Science  DBMS  Total  Percentage Result Grade
Teerth      51            29    95    175   58.333333   Pass     E
Naitik      51            39    40    130   43.333333   Fail     F
Riya        51            61    79    191   63.666667   Pass     D
Fenil       98            98   100    296   98.666667   Pass     A

In [50]:
df3.describe()

python  Data Science        DBMS       Total  Percentage
count    4.00      4.000000    4.000000    4.000000    4.000000
mean    62.75     56.750000   78.500000  198.000000   66.000000
std     23.50     30.576407   27.184554   70.251928   23.417309
min     51.00     29.000000   40.000000  130.000000   43.333333
25%     51.00     36.500000   69.250000  163.750000   54.583333
50%     51.00     50.000000   87.000000  183.000000   61.000000
75%     62.75     70.250000   96.250000  217.250000   72.416667
max     98.00     98.000000  100.000000  296.000000   98.666667

In [51]:
df3.info

<bound method DataFrame.info of         python  Data Science  DBMS  Total  Percentage Result Grade
Teerth      51            29    95    175   58.333333   Pass     E
Naitik      51            39    40    130   43.333333   Fail     F
Riya        51            61    79    191   63.666667   Pass     D
Fenil       98            98   100    296   98.666667   Pass     A>

In [52]:
dict_list = df3.to_dict(orient='list')
dict_list

{'python': [51, 51, 51, 98],
 'Data Science': [29, 39, 61, 98],
 'DBMS': [95, 40, 79, 100],
 'Total': [175, 130, 191, 296],
 'Percentage': [58.333333333333336,
  43.333333333333336,
  63.66666666666667,
  98.66666666666667],
 'Result': ['Pass', 'Fail', 'Pass', 'Pass'],
 'Grade': ['E', 'F', 'D', 'A']}

In [54]:
productId = [101, 102, 103, 104, 105]
productName = ['Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Camera']
productPrice = [500, 700, 300, 100, 900]

df= pd.DataFrame({'Product ID': productId, 'Product Name': productName, 'Product Price': productPrice})
df['Product Price'] += 500
df

Product ID Product Name  Product Price
0         101       Laptop           1000
1         102   Smartphone           1200
2         103       Tablet            800
3         104   Headphones            600
4         105       Camera           1400

TASK:-2

In [57]:
import pandas as pd

In [59]:
sal = pd.read_csv('Salaries.csv')
sal

C:\Users\teerth\AppData\Local\Temp\ipykernel_16724\1798377461.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv')


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [60]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [61]:
sal.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [65]:
average_basepay = sal['BasePay'].mean()
average_basepay

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [66]:
sal['OvertimePay'].max()

TypeError: '>=' not supported between instances of 'float' and 'str'

In [67]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [68]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [69]:
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].max()]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN

In [70]:
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle BasePay OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch    0.00        0.00   

       OtherPay Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653  -618.13     0.00   -618.13           -618.13  2014    NaN   

               Agency Status  
148653  San Francisco     PT

In [72]:
sal.groupby('Year').mean()['BasePay']

C:\Users\teerth\AppData\Local\Temp\ipykernel_16724\3145117890.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sal.groupby('Year').mean()['BasePay']


KeyError: 'BasePay'

In [73]:
sal['JobTitle'].nunique()

2159

In [74]:
sal['JobTitle'].value_counts().head(5)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [75]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1)

202

In [76]:
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False

In [77]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

627

In [78]:
sal['title_len'] = sal['JobTitle'].apply(len)

In [79]:
sal[['title_len','TotalPayBenefits']].corr()

title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

In [4]:
import pandas as pd
df=pd.DataFrame({'key':['A','B','C','A','B','C'],
                'data':range(6)},columns=['key','data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [5]:
data={'Company':['Google','Google','MSFT','MSFT','FB','FB','FB'],
     'Person':['Sam','Charlie','Amy','Vanssa','Carl','Sarah','Liza'],
     'Sales':[200,120,340,124,243,350,456]}
data

{'Company': ['Google', 'Google', 'MSFT', 'MSFT', 'FB', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanssa', 'Carl', 'Sarah', 'Liza'],
 'Sales': [200, 120, 340, 124, 243, 350, 456]}

In [7]:
df=pd.DataFrame(data)
df

Company   Person  Sales
0  Google      Sam    200
1  Google  Charlie    120
2    MSFT      Amy    340
3    MSFT   Vanssa    124
4      FB     Carl    243
5      FB    Sarah    350
6      FB     Liza    456

In [9]:
by_comp=df.groupby('Company')

In [10]:
by_comp.mean('Sales')

Sales
Company            
FB       349.666667
Google   160.000000
MSFT     232.000000

In [11]:
by_comp.describe()

Sales                                                           
        count        mean         std    min    25%    50%    75%    max
Company                                                                 
FB        3.0  349.666667  106.500391  243.0  296.5  350.0  403.0  456.0
Google    2.0  160.000000   56.568542  120.0  140.0  160.0  180.0  200.0
MSFT      2.0  232.000000  152.735065  124.0  178.0  232.0  286.0  340.0

In [12]:
by_comp.describe().transpose()

Company              FB      Google        MSFT
Sales count    3.000000    2.000000    2.000000
      mean   349.666667  160.000000  232.000000
      std    106.500391   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    296.500000  140.000000  178.000000
      50%    350.000000  160.000000  232.000000
      75%    403.000000  180.000000  286.000000
      max    456.000000  200.000000  340.000000

In [13]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                index=[0,1,2,3])

In [14]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},
                index=[4,5,6,7])

In [15]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])

In [16]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A0   B0   C0   D0
5    A1   B1   C1   D1
6    A2   B2   C2   D2
7    A3   B3   C3   D3
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [17]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A0   B0   C0   D0  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A1   B1   C1   D1  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A2   B2   C2   D2  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A3   B3   C3   D3  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [18]:
left=pd.DataFrame({'key':['k0','k1','k0','k3'],
                 'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3']})

In [26]:
right=pd.DataFrame({'key':['k0','k3','k2','k3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']})

In [27]:
display(df1,df2,df3,pd.concat([df1,df2,df3]))

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

A   B   C   D
4  A0  B0  C0  D0
5  A1  B1  C1  D1
6  A2  B2  C2  D2
7  A3  B3  C3  D3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A0   B0   C0   D0
5    A1   B1   C1   D1
6    A2   B2   C2   D2
7    A3   B3   C3   D3
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

MERGING

In [28]:
display(left,right,pd.merge(left,right,how='inner',on='key'))

key   A   B
0  k0  A0  B0
1  A1  A1  B1
2  A2  A2  B2
3  A3  A3  B3

key   C   D
0  k0  C0  D0
1  k3  C1  D1
2  k2  C2  D2
3  k3  C3  D3

key   A   B   C   D
0  k0  A0  B0  C0  D0

In [30]:
display(left,right,pd.merge(left,right,how='outer',on=['key']),
       pd.merge(left,right,how='inner',on=['key']),
       pd.merge(left,right,how='left',on=['key']),
       pd.merge(left,right,how='right',on=['key']))

key   A   B
0  k0  A0  B0
1  A1  A1  B1
2  A2  A2  B2
3  A3  A3  B3

key   C   D
0  k0  C0  D0
1  k3  C1  D1
2  k2  C2  D2
3  k3  C3  D3

key    A    B    C    D
0  k0   A0   B0   C0   D0
1  A1   A1   B1  NaN  NaN
2  A2   A2   B2  NaN  NaN
3  A3   A3   B3  NaN  NaN
4  k3  NaN  NaN   C1   D1
5  k3  NaN  NaN   C3   D3
6  k2  NaN  NaN   C2   D2

key   A   B   C   D
0  k0  A0  B0  C0  D0

key   A   B    C    D
0  k0  A0  B0   C0   D0
1  A1  A1  B1  NaN  NaN
2  A2  A2  B2  NaN  NaN
3  A3  A3  B3  NaN  NaN

key    A    B   C   D
0  k0   A0   B0  C0  D0
1  k3  NaN  NaN  C1  D1
2  k2  NaN  NaN  C2  D2
3  k3  NaN  NaN  C3  D3

In [33]:
left=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3']},
                 index=['K0','K1','K2','K3'])

In [34]:
right=pd.DataFrame({'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                 index=['K0','K4','K2','K3'])

In [36]:
display(left.join(right,how='outer'),left.join(right,how='inner'))

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
K4  NaN  NaN   C1   D1

A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2
K3  A3  B3  C3  D3

In [5]:
import pandas as pd
df=pd.read_csv("Ecommerce Purchases")
df

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
...                                                 ...    ...      ...   
9995      966 Castaneda Locks\nWest Juliafurt, CO 96415  92 XI       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   
9997              Unit 4434 Box 6343\nDPO AE 28026-0283  74 Zh       AM   
9998               0096 English Rest\nRoystad, IA 12457  74 cL       PM   
9999     40674 Barrett Stravenue\nGrimesville, WI 79682  64 Hr       AM   

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1     Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   
...                                                 ...   
9995  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
9997  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
9998  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...   
9999  Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...   

                              Company       Credit Card CC Exp Date  \
0                     Martinez-Herman  6011929061123406       02/20   
1     Fletcher, Richards and Whitaker  3337758169645356       11/18   
2          Simpson, Williams and Pham      675957666125       08/19   
3     Williams, Marshall and Buchanan  6011578504430710       02/24   
4           Brown, Watson and Andrews  6011456623207998       10/25   
...                               ...               ...         ...   
9995                    Randall-Sloan   342945015358701       03/22   
9996         Hale, Collins and Wilson   210033169205009       07/25   
9997                     Anderson Ltd  6011539787356311       05/21   
9998                         Cook Inc   180003348082930       11/17   
9999                       Greene Inc  4139972901927273       02/19   

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit   
1                  561                   Mastercard   
2                  699                 JCB 16 digit   
3                  384                     Discover   
4                  678  Diners Club / Carte Blanche   
...                ...                          ...   
9995               838                 JCB 15 digit   
9996               207                 JCB 16 digit   
9997                 1                VISA 16 digit   
9998               987             American Express   
9999               302                 JCB 15 digit   

                               Email                                     Job  \
0                  pdunlap@yahoo.com  Scientist, product/process development   
1                 anthony41@reed.com                       Drilling engineer   
2     amymiller@morales-harrison.com                Customer service manager   
3        brent16@olson-robinson.info                       Drilling engineer   
4        christopherwright@gmail.com                             Fine artist   
...                              ...                                     ...   
9995          iscott@wade-garner.com                              Printmaker   
9996              mary85@hotmail.com                         Energy engineer   
9997               tyler16@gmail.com                      Veterinary surgeon   
9998         elizabethmoore@reid.net                Local government officer   
9999           rachelford@vaughn.com        

In [6]:
df.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [8]:
df.tail()

Address    Lot AM or PM  \
9995      966 Castaneda Locks\nWest Juliafurt, CO 96415  92 XI       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   
9997              Unit 4434 Box 6343\nDPO AE 28026-0283  74 Zh       AM   
9998               0096 English Rest\nRoystad, IA 12457  74 cL       PM   
9999     40674 Barrett Stravenue\nGrimesville, WI 79682  64 Hr       AM   

                                           Browser Info  \
9995  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
9997  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
9998  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...   
9999  Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...   

                       Company       Credit Card CC Exp Date  \
9995             Randall-Sloan   342945015358701       03/22   
9996  Hale, Collins and Wilson   210033169205009       07/25   
9997              Anderson Ltd  6011539787356311       05/21   
9998                  Cook Inc   180003348082930       11/17   
9999                Greene Inc  4139972901927273       02/19   

      CC Security Code       CC Provider                    Email  \
9995               838      JCB 15 digit   iscott@wade-garner.com   
9996               207      JCB 16 digit       mary85@hotmail.com   
9997                 1     VISA 16 digit        tyler16@gmail.com   
9998               987  American Express  elizabethmoore@reid.net   
9999               302      JCB 15 digit    rachelford@vaughn.com   

                           Job       IP Address Language  Purchase Price  
9995                Printmaker    29.73.197.114       it           82.21  
9996           Energy engineer   121.133.168.51       pt           25.63  
9997        Veterinary surgeon    156.210.0.254       el           83.98  
9998  Local government officer     55.78.26.143       es           38.84  
9999    Embryologist, clinical  176.119.198.199       el           67.59

In [11]:
df.describe()

Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [16]:
df[df['Language']=="en"].count()


Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [18]:
df[df['Job']=="Lawyer"].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [20]:
df[df['AM or PM']=="AM"].count()

Address             4932
Lot                 4932
AM or PM            4932
Browser Info        4932
Company             4932
Credit Card         4932
CC Exp Date         4932
CC Security Code    4932
CC Provider         4932
Email               4932
Job                 4932
IP Address          4932
Language            4932
Purchase Price      4932
dtype: int64

In [21]:
df[df['AM or PM']=="PM"].count()

Address             5068
Lot                 5068
AM or PM            5068
Browser Info        5068
Company             5068
Credit Card         5068
CC Exp Date         5068
CC Security Code    5068
CC Provider         5068
Email               5068
Job                 5068
IP Address          5068
Language            5068
Purchase Price      5068
dtype: int64

In [22]:
df['Job'].value_counts().head()

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

In [24]:
df[df['Lot']=="90 WT"]['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

In [26]:
df[df['Credit Card']==4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [27]:
df[(df['CC Provider']=='American Express')&(df['Purchase Price']>95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64